USE [BDEJEMPLO2]
GO

/****** Object:  Database [BDEJEMPLO2]    Script Date: 15/08/2025 11:00:57 a. m. ******/
CREATE DATABASE [BDEJEMPLO2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDEJEMPLO2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BDEJEMPLO2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BDEJEMPLO2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BDEJEMPLO2_log.ldf' , SIZE = 4224KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDEJEMPLO2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDEJEMPLO2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDEJEMPLO2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDEJEMPLO2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDEJEMPLO2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDEJEMPLO2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET RECOVERY FULL 
GO

ALTER DATABASE [BDEJEMPLO2] SET  MULTI_USER 
GO

ALTER DATABASE [BDEJEMPLO2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDEJEMPLO2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDEJEMPLO2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDEJEMPLO2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BDEJEMPLO2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDEJEMPLO2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BDEJEMPLO2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BDEJEMPLO2] SET  READ_WRITE 
GO


SELECT 
    C.CompanyName AS [Cliente],
    ROUND(SUM(OD.Quantity * OD.UnitPrice * (1 - OD.Discount)), 2) AS Ingreso_Total
FROM [Order Details] AS OD
INNER JOIN Orders AS O
    ON O.OrderID = OD.OrderID
INNER JOIN Customers AS C
    ON O.CustomerID = C.CustomerID
WHERE DATEPART(YEAR, O.OrderDate) = 1997
GROUP BY C.CompanyName
ORDER BY Ingreso_Total DESC;